# Generated by Django 5.1.6 on 2025-03-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='registrant_pictures/')),
                ('gender', models.CharField(choices=[('Feto', 'Feto'), ('Mane', 'Mane')], max_length=10)),
                ('institution', models.CharField(choices=[('TIC TIMOR', 'TIC TIMOR'), ('MTC', 'MTC')], max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('access_pass', models.CharField(blank=True, max_length=10, unique=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
