# Generated by Django 5.1.6 on 2025-03-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0002_registrant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
