# Generated by Django 5.1.6 on 2025-03-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0003_alter_registrant_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrant',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejistu.institution'),
        ),
    ]
