# Generated by Django 5.1.6 on 2025-03-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0004_institution_alter_registrant_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='access_pass_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
