# Generated by Django 5.1.6 on 2025-03-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0005_institution_access_pass_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='quota',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
