# Generated by Django 5.1.6 on 2025-03-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0006_institution_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='access_pass',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='No. Electoral'),
        ),
    ]
