# Generated by Django 5.1.6 on 2025-03-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0008_accesspass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='access_pass',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
