# Generated by Django 5.1.6 on 2025-03-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0009_alter_registrant_access_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='access_pass',
            field=models.CharField(max_length=10),
        ),
    ]
