# Generated by Django 5.1.6 on 2025-03-11 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0010_alter_registrant_access_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='access_pass',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rejistu.accesspass'),
        ),
    ]
