# Generated by Django 5.1.6 on 2025-03-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejistu', '0012_registrant_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='face_encoding',
        ),
    ]
