# Generated by Django 5.1.6 on 2025-03-15 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='image',
        ),
        migrations.AddField(
            model_name='registrant',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='registrant_photos/'),
            preserve_default=False,
        ),
    ]
